#!/bin/bash

#Requires Inkscape to be installed.

#This script scales and creates images at the correct dpi level for Android.
#When creating svg files set the image size to the size that you want your mdpi images to be.


function processImage {
	echo "Processing $1"

	file=$(basename $1)

	case $OSTYPE in
	darwin*)
		inkscape= "/Applications/Inkscape.app/Contents/Resources/bin/inkscape"
		;;
	linux-gnu*)
		inkscape="inkscape"
		;;
	esac

	$inkscape -d 320 -e $2/res/drawable-xhdpi/${file/.svg}.png $1 >& /dev/null
	$inkscape -d 240 -e $2/res/drawable-hdpi/${file/.svg}.png $1 >& /dev/null
	$inkscape -d 160 -e $2/res/drawable-mdpi/${file/.svg}.png $1 >& /dev/null
	$inkscape -d 120 -e $2/res/drawable-ldpi/${file/.svg}.png $1 >& /dev/null
}

timestamp="201002211200.00"

tempfile=mktemp
trap "rm -f $tempfile" SIGINT SIGTERM
touch -t $timestamp $tempfile

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

for f in $(find $1 -name *.svg -type f -newer $tempfile);
do
	if [[ "$f" == *.9.svg* ]]; then
		$DIR/gen9patch.py $f $2
	else 
		processImage $f $2
	fi
done

rm -f $tempfile
